-- MySQL Script generated by MySQL Workbench
-- Thu Jan 30 17:33:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tiendaVirtual
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tiendaVirtual
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tiendaVirtual` DEFAULT CHARACTER SET utf8 ;
USE `tiendaVirtual` ;

-- -----------------------------------------------------
-- Table `tiendaVirtual`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaVirtual`.`Producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` MEDIUMTEXT NULL,
  `precio` INT NULL,
  `foto` VARCHAR(45) NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaVirtual`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaVirtual`.`Usuario` (
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `direccion_correo` VARCHAR(45) NULL,
  `direccion_fisica` VARCHAR(45) NULL,
  PRIMARY KEY (`nombre_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaVirtual`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaVirtual`.`Pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `Usuario_nombre_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pedido`, `Usuario_nombre_usuario`),
  INDEX `fk_Pedido_Usuario1_idx` (`Usuario_nombre_usuario` ASC) ,
  CONSTRAINT `fk_Pedido_Usuario1`
    FOREIGN KEY (`Usuario_nombre_usuario`)
    REFERENCES `tiendaVirtual`.`Usuario` (`nombre_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaVirtual`.`Cesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaVirtual`.`Cesta` (
  `id_visitante` MEDIUMTEXT NULL,
  `id_producto` INT NULL,
  `cantidad` INT NULL,
  INDEX `id_producto_idx` (`id_producto` ASC) ,
  CONSTRAINT `id_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `tiendaVirtual`.`Producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaVirtual`.`Producto_has_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaVirtual`.`Producto_has_Pedido` (
  `Producto_id_producto` INT NOT NULL,
  `Pedido_id_pedido` INT NOT NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`Producto_id_producto`, `Pedido_id_pedido`),
  INDEX `fk_Producto_has_Pedido_Pedido1_idx` (`Pedido_id_pedido` ASC) ,
  INDEX `fk_Producto_has_Pedido_Producto_idx` (`Producto_id_producto` ASC) ,
  CONSTRAINT `fk_Producto_has_Pedido_Producto`
    FOREIGN KEY (`Producto_id_producto`)
    REFERENCES `tiendaVirtual`.`Producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_id_pedido`)
    REFERENCES `tiendaVirtual`.`Pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
