<?php
// necesitamos la trayectoria de la URL para formar las rutas:
global $URL_PATH;
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="noindex,nofollow">
    <title>
        <?php \dawfony\Ti::startBlock("title"); ?>
        Viaje privado
        <?php \dawfony\Ti::endBlock(); ?>
    </title>
    <style>
        .error {
            color: red;
        }
        img {
            max-width: 100px;
        }
    </style>
    <link rel="stylesheet" type="text/css" href="<?= $URL_PATH ?>/css/mainView.css">
    <?php /* Bootstrap.CDN */ ?>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <?php /* Font awesome CDN */ ?>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <?php /* Animate.css CDN */ ?>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
    <?php /* Javascript de este proyecto */ ?>
    <script src="<?= $URL_PATH ?>/js/main.js"></script>

    <?php /*Para añadir lineas al head desde las plantillas derivadas*/ ?>
    <?php \dawfony\Ti::startBlock("head"); ?>
    <?php \dawfony\Ti::endBlock(); ?>
</head>

<body class="container">
<script>var URL_PATH = "<?= $URL_PATH ?>";</script>
    <div class="jumbotron shadow" id="mainjumbo">
        <div class="text-center myfont">
            <h1>Viaje privado</h1>
        </div>
    </div>
    <nav>
    <a href="#" id="verCarrito"><i class="fa fa-cart-arrow-down" style="font-size:48px;"></i></a>
    <span id="carrito"><?= $cantidadPedidos["contador"] ?></span>
    <div id="cosasCarrito">
        <div id="listaPedidos"></div>
        <a href="<?= $URL_PATH ?>/verPedidos" id="botonRealizarCompra">REALIZAR COMPRA</a>
    </div>
    </nav>
    <script>
        let url = "<?= $URL_PATH ?>/";
    </script>
    
    <script src="<?= $URL_PATH ?>/js/annadirACarrito.js"></script>
    <?php \dawfony\Ti::startBlock("content"); ?>
    Bloque "content" en Main view.
    Sustituye en las clases que extiende.

    <?php \dawfony\Ti::endBlock(); ?>
    <footer class="rounded p-4 mt-2 text-center bg-light myfont">
        © <?= date("Y") ?> 2ºDAW
    </footer>
</body>

</html>